[project]
name = "metasploitmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.95.0",
    "uvicorn[standard]>=0.22.0",
    "pymetasploit3>=1.0.6",
    "mcp>=1.6.0",
    "fastmcp>=2.10.3"

]
